### ISSUE TITLE
Figure out building and publishing

### ISSUE THREAD

**Issue by mmcfarland** [azavea/usace-flood-geoprocessing#6]
Unless we can get signoff to make this a public repo, we'll have to get creative for how we build and publish versions of this JAR.  Probably a Jenkins job which has keys to needed to create GH releases, or similar.

**Comment by lewfish** [comment]
Also, change the provisioning to get the jar from the Github release.

**Comment by kdeloach** [comment]
Should we update the milestone on this issue?
